/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Rifat
 */
public class Credits extends javax.swing.JFrame {

    /**
     * Creates new form Credits
     */
    public Credits() {
        initComponents();
        setTitle("Credit Page");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        credits = new javax.swing.JPanel();
        NameRifat = new javax.swing.JLabel();
        IdRifat = new javax.swing.JLabel();
        NameArgha = new javax.swing.JLabel();
        IdArgha = new javax.swing.JLabel();
        NameZim = new javax.swing.JLabel();
        IdZim = new javax.swing.JLabel();
        Return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        credits.setPreferredSize(new java.awt.Dimension(766, 630));
        credits.setLayout(null);

        NameRifat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NameRifat.setForeground(new java.awt.Color(51, 51, 255));
        NameRifat.setText("Submitted By");
        credits.add(NameRifat);
        NameRifat.setBounds(20, 10, 310, 50);

        IdRifat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        IdRifat.setForeground(new java.awt.Color(51, 51, 255));
        IdRifat.setText("Rakib Hossian Rifat");
        credits.add(IdRifat);
        IdRifat.setBounds(40, 60, 220, 44);

        NameArgha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NameArgha.setForeground(new java.awt.Color(51, 51, 255));
        NameArgha.setText("16-02-04-099");
        credits.add(NameArgha);
        NameArgha.setBounds(40, 90, 310, 51);

        IdArgha.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        IdArgha.setForeground(new java.awt.Color(51, 51, 255));
        IdArgha.setText("16.02.04.110");
        credits.add(IdArgha);
        IdArgha.setBounds(40, 180, 259, 34);

        NameZim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NameZim.setForeground(new java.awt.Color(51, 51, 255));
        NameZim.setText("Yeasir Arafat Zim");
        credits.add(NameZim);
        NameZim.setBounds(40, 230, 294, 37);

        IdZim.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        IdZim.setForeground(new java.awt.Color(51, 51, 255));
        IdZim.setText("16.02.04.093");
        credits.add(IdZim);
        IdZim.setBounds(40, 260, 216, 41);

        Return.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        credits.add(Return);
        Return.setBounds(579, 549, 133, 35);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Argha Shipan Sarker");
        credits.add(jLabel1);
        jLabel1.setBounds(40, 140, 230, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Submitted To");
        credits.add(jLabel2);
        jLabel2.setBounds(240, 360, 190, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Golam Rhman Tushar Sir");
        jLabel3.setToolTipText("");
        credits.add(jLabel3);
        jLabel3.setBounds(180, 410, 270, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        FristPage four = new FristPage();
        credits.setVisible(false);
        dispose();
        four.setVisible(true);

    }//GEN-LAST:event_ReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdArgha;
    private javax.swing.JLabel IdRifat;
    private javax.swing.JLabel IdZim;
    private javax.swing.JLabel NameArgha;
    private javax.swing.JLabel NameRifat;
    private javax.swing.JLabel NameZim;
    private javax.swing.JButton Return;
    private javax.swing.JPanel credits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
